"""Rename earthquake

Revision ID: c6903c8e78c2
Revises: af452d27593e
Create Date: 2023-11-15 08:54:01.710575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6903c8e78c2'
down_revision = 'af452d27593e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('earthquake', 'earthquakes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('earthquakes', 'earthquake')
    # ### end Alembic commands ###
